name: test runner for morphing code
on: push
jobs:
        testrun:
                runs-on: ubuntu-latest
                steps:
                        - name: Check out code
                          uses: actions/checkout@v2

                        - name: install dependencies
                          run: pip install numpy
                          
                        - run: python3 ./morpher.py

